interface Draft {
  type: string
  title: string
  id: string
  updated: number
  imageCount?: number
}

type TemplateType = 'standard' | 'detailed' | 'quick'

interface TemplateOption {
  id: TemplateType
  label: string
  description: string
}

export const PR_TEMPLATES: TemplateOption[] = [
  { id: 'standard', label: 'Standard', description: 'Professional overview with change log' },
  { id: 'detailed', label: 'Detailed', description: 'Full breakdown grouped by type' },
  { id: 'quick', label: 'Quick', description: 'Minimal bullet summary' },
]

function fmt(d: number) {
  return new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })
}

function draftTable(drafts: Draft[]): string {
  const rows = drafts.map(d =>
    `| ${d.type === 'mission' ? '🎯' : d.type === 'announcement' ? '📢' : '👥'} ${escapeMd(d.title)} | \`${d.id}\` | ${d.imageCount ? d.imageCount + ' img' : '—'} | ${fmt(d.updated)} |`
  ).join('\n')
  return [
    '| Type | ID | Assets | Last Update |',
    '|---|---|---|---|',
    rows,
  ].join('\n')
}

function countByType(drafts: Draft[]) {
  let m = 0, a = 0, mb = 0
  for (const d of drafts) {
    if (d.type === 'mission') m++
    else if (d.type === 'announcement') a++
    else mb++
  }
  return { mission: m, announcement: a, members: mb }
}

function escapeMd(s: string): string {
  return s.replace(/\|/g, '\\|')
}

function generateStandard(drafts: Draft[]): string {
  const c = countByType(drafts)
  const totalImgs = drafts.reduce((s, d) => s + (d.imageCount || 0), 0)
  const parts: string[] = []

  parts.push('# 📋 Admin Content Update\n')
  parts.push(`**Generated:** ${fmt(Date.now())}  `)
  parts.push(`**Branch:** \`main\` (via admin panel)  `)
  parts.push(`**Changes:** ${drafts.length} draft${drafts.length !== 1 ? 's' : ''} · ${totalImgs} image${totalImgs !== 1 ? 's' : ''}\n`)

  parts.push('---\n')

  parts.push('## 📊 Summary\n')
  const summary = [
    `- 🎯 **Missions:** ${c.mission} update${c.mission !== 1 ? 's' : ''}`,
    `- 📢 **Announcements:** ${c.announcement} update${c.announcement !== 1 ? 's' : ''}`,
    `- 👥 **Members:** ${c.members > 0 ? 'Updated' : 'No changes'}`,
  ]
  if (totalImgs > 0) {
    summary.push(`- 🖼️ **Total images uploaded:** ${totalImgs}`)
  }
  parts.push(summary.join('\n'))
  parts.push('')

  if (drafts.length > 0) {
    parts.push('## 📦 Files Changed\n')
    parts.push(draftTable(drafts))
    parts.push('')
  }

  parts.push('---')
  parts.push('_🤖 This PR was created automatically via the RU Admin Panel._')

  return parts.join('\n')
}

function generateDetailed(drafts: Draft[]): string {
  const parts: string[] = []

  parts.push('# 📦 Content Update — Detailed Breakdown\n')

  parts.push('## 🔍 Overview\n')
  parts.push('| Metric | Value |')
  parts.push('|---|---|')
  parts.push(`| **Date** | ${fmt(Date.now())} |`)
  parts.push(`| **Total drafts** | ${drafts.length} |`)
  parts.push(`| **Images** | ${drafts.reduce((s, d) => s + (d.imageCount || 0), 0)} |`)
  parts.push('')

  const missions = drafts.filter(d => d.type === 'mission')
  const announcements = drafts.filter(d => d.type === 'announcement')
  const members = drafts.filter(d => d.type === 'members')

  if (missions.length > 0) {
    parts.push('## 🎯 Mission Updates\n')
    parts.push('| Title | ID | Images | Last Modified |')
    parts.push('|---|---|---|---|')
    for (const d of missions) {
      parts.push(`| **${escapeMd(d.title)}** | \`${d.id}\` | ${d.imageCount || 0} | ${fmt(d.updated)} |`)
    }
    parts.push('')
  }

  if (announcements.length > 0) {
    parts.push('## 📢 Announcement Updates\n')
    parts.push('| Title | ID | Image | Last Modified |')
    parts.push('|---|---|---|---|')
    for (const d of announcements) {
      parts.push(`| **${escapeMd(d.title)}** | \`${d.id}\` | ${d.imageCount ? '✅' : '—'} | ${fmt(d.updated)} |`)
    }
    parts.push('')
  }

  if (members.length > 0) {
    parts.push('## 👥 Members Data\n')
    parts.push('The members roster has been updated.\n')
  }

  const allFiles: string[] = []
  for (const d of drafts) {
    if (d.type === 'mission') {
      allFiles.push(`- \`src/mission/${d.id}/info.json\``)
      for (let i = 0; i < (d.imageCount || 0); i++) {
        allFiles.push(`- \`src/mission/${d.id}/img-${String(i + 1).padStart(2, '0')}.jpg\``)
      }
    } else if (d.type === 'announcement') {
      allFiles.push(`- \`src/announcements/main/${d.id}.json\``)
      if (d.imageCount && d.imageCount > 0) {
        allFiles.push(`- \`src/announcements/assets/${d.id}-image.jpg\``)
      }
    } else if (d.type === 'members') {
      allFiles.push('- `src/info/members.json`')
    }
  }

  if (allFiles.length > 0) {
    parts.push('## 📁 Affected Files\n')
    parts.push(allFiles.join('\n'))
    parts.push('')
  }

  parts.push('---')
  parts.push('_PR generated by RU Admin Panel_')

  return parts.join('\n')
}

function generateQuick(drafts: Draft[]): string {
  const bullets = drafts.map(d =>
    `- **${d.type === 'mission' ? 'Mission' : d.type === 'announcement' ? 'Announcement' : 'Members'}**: ${d.title}${d.imageCount ? ` (${d.imageCount} img)` : ''}`
  ).join('\n')

  return [
    '## 🚀 Quick Update',
    '',
    bullets,
    '',
    '---',
    '_Auto-generated PR_',
  ].join('\n')
}

export function generatePRBody(drafts: Draft[], template: TemplateType): string {
  if (template === 'detailed') return generateDetailed(drafts)
  if (template === 'quick') return generateQuick(drafts)
  return generateStandard(drafts)
}
